name: snapshot publish

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull Request Number'
        required: true

jobs:
  snapshot-publish:
    uses: test-changeit/operation/.github/workflows/reusable-snapshot-publish.yml@dev
    with:
      pr: ${{ inputs.pr }}
      enable_discord_announce: true
    secrets: inherit
